name: Build Release APK

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Aqua

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_FILE: keystore.jks
      VERSION_NAME: ${{ github.event.inputs.version_name || github.ref_name }}
      RELEASE_VERSION_CODE: ${{ github.event.inputs.release_code || 999 }}
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > $KEYSTORE_FILE
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_FILE: app/keystore.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease -PversionName="$VERSION_NAME" -PreleaseCode="$RELEASE_VERSION_CODE"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
